### ISSUE TITLE
Q. Representation unification with illumina dataset

### ISSUE THREAD

**Issue by quito418** [HKU-BAL/Clair3#103]
Hi, thank you foru

I am currently trying to train the Clair3 model with Illumina dataset.

I followed the representation unification [document ](https://github.com/HKU-BAL/Clair3/blob/main/docs/representation_unification.md) to generate unified vcf truth set.

But I wasn't able to run `UnifyRepresentation`, step 5 for Illumina reads.
The error is that `chr.bam.chunkctgstart_chunkctgend` does not exists (CreateTensorFullAlignment.py).
![image](https://user-images.githubusercontent.com/26645270/167054682-1ef83402-e3cc-4372-9bd3-496690562621.png)

Files in the directory are as below.
![image](https://user-images.githubusercontent.com/26645270/167054723-1f9d9937-faae-4d29-80f1-86a4c9d4b8b2.png)

I'm not sure but is representation unification also important for short reads?

Thanks!

**Comment by zhengzhenxian** [comment]
Thank you for reporting. Yes, representation unification is also essential for short-read and we found your error was due to a file naming bug in Clair3. We fixed the code and updated GitHub (file [CreateTensorFullAlignment.py](https://github.com/HKU-BAL/Clair3/blob/main/preprocess/CreateTensorFullAlignment.py), commit [9fb751df111bfc6c52a59ab7eae49ac3b15ee47f](https://github.com/HKU-BAL/Clair3/commit/9fb751df111bfc6c52a59ab7eae49ac3b15ee47f)).  You can pull the new code to fix the problem, or do you want us to update bioconda or docker so you can try out the new code?

**Comment by quito418** [comment]
I will use the github, thanks for your prompt reply!

**Comment by quito418** [comment]
Now the unification steps work well, and I have one question regarding the `hap.py` benchmark result.

My `hap.py` benchmark result shows that some of the results are different (below image), is it the expected behavior? (I thought the result should be 100% identical, am I missing something).

![image](https://user-images.githubusercontent.com/26645270/167329542-608bd73e-7819-4c56-a7ac-d6d9579537c9.png)


Thanks

**Comment by aquaskyline** [comment]
Which result are you comparing against? And were you using a self-trained model or our pre-trained models? Regarding the results shown in Clair3's preprint, you can find the VCF files at http://bio8.cs.hku.hk/clair3/analysis_result/.

**Comment by quito418** [comment]
I compared unified_vcf against the original vcf with `hap.py` (not using model prediction).

**Comment by aquaskyline** [comment]
Understood. It is expected. Depending on the input (coverage, platform, library prep protocol), some truth variants might be removed from the unified VCF. Thus you can see that the Precision in your result is very high, but the recall is reduced. The purpose of generating a unified VCF (instead of using the truth variants directly) is to guarantee that the variants used for model training is really what the alignment shows, so the training samples won't confuse the model. In reality, some truth variants could have no alignment covered, or a different alignment pattern that mismatches are not centered at the truth variant locus. Thes truth variants are removed from unified VCF, thus not used for model training.

**Comment by quito418** [comment]
Thank you for your kind response!
