### ISSUE TITLE
clair3_ont_quick_demo.sh poor parallel scalability

### ISSUE THREAD

**Issue by LorienLV** [HKU-BAL/Clair3#107]
We are using `clair3_ont_quick_demo.sh` to benchmark two different compute nodes with 48 physical threads. Our understanding of the documentation is that Clair3 splits the input into small chunks (13 by default for `clair3_ont_quick_demo.sh`) and assigns each chunk to a pool of 4 threads. Each pool of threads can work with up to 3 chunks simultaneously (`--threads` parameter definition: "The chunks being processed simultaneously is `ceil($threads/4)*3`"). However, what we are experiencing is that each chunk is assigned to one single thread while the number of chunks processed simultaneously is `ceil($threads/4)*3`. Therefore, some threads are idle. For example, if we execute with `--threads=48`, only 36 chunks are processed simultaneously.

In `scripts/clair3_CallVar.sh` we observe that the parallel command runs up to `ceil($threads/4)*3` jobs (chunks) in parallel. In `clair3/CallVariants.py::call_variants()` function, the main loop only spawns two threads on each iteration (one for `load_mini_batch()` and another for `batch_output_method()`), and it joins the threads before starting a new iteration. This seems to confirm our experience. Are we missing something?

Also, what is the reason behind setting a chunk size (5Mbps) by default instead of splitting the input in `$threads` chunks? In our understanding, the best possible parallel scalability will be obtained when all chunks have similar sizes, and all chunks are processed in parallel.

**Comment by aquaskyline** [comment]
The processing of each chuck is not single-threaded all the time. During model inference, the CPU utilization of each chuck varies between 100% to 400%. The average CPU utilization of a chuck is around 130%. Therefore, "$THREADS/4*3" is a heuristic empirically designed to fully utilize the available number of $THREADS most of the time while not too frequently overcommitting CPU resources. Clair3 uses Tensorflow, and it is not easy to get fine control of TF's threading.

Setting a fixed chunk size instead of splitting the input according to $THREADS is just a choice of design that I wish to constrain the complexity of each chuck, and I have no assumption of the computational resources that are available to Clair3 (could be a Raspberry Pi or a grid with thousands of nodes).

**Comment by LorienLV** [comment]
I did not know Tensorflow used more than 1 thread by default. It is a problem that you can not manually control this... We will try a bigger input and tweak chunk sizes to get better parallel performance. Thank you!
