### ISSUE TITLE
Low allele-frequencies and InDels, despite setting appropriate filters

### ISSUE THREAD

**Issue by SebastianMeyer1989** [HKU-BAL/Clair3#123]
Hi there,
I am doing a few different clair3 runs with the parameters "--call_snp_only" and "--snp_min_af=0.25".
Even so I am getting some calls like these:

```
EFAU004_00073	112	.	T	A	18.61	PASS	F	GT:GQ:DP:AF	0/1:18:461:0.2169
EFAU004_00116	320	.	T	A	9.07	PASS	F	GT:GQ:DP:AF	1/1:9:210:0.2048
EFAU004_00425	438	.	G	A	7.16	PASS	F	GT:GQ:DP:AF	0/1:7:300:0.2233
EFAU004_01676	103	.	G	T	9.02	PASS	F	GT:GQ:DP:AF	0/1:9:269:0.2342
EFAU004_01783	179	.	G	A	2.58	PASS	F	GT:GQ:DP:AF	0/1:2:270:0.2148
EFAU004_02005	352	.	T	A	10.43	PASS	F	GT:GQ:DP:AF	0/1:10:340:0.1676
EFAU004_02005	366	.	G	A	12.81	PASS	F	GT:GQ:DP:AF	0/1:12:341:0.2082
EFAU004_02005	403	.	C	A	9.69	PASS	F	GT:GQ:DP:AF	0/1:9:342:0.1959
EFAU004_02103	310	.	T	C	8.38	PASS	F	GT:GQ:DP:AF	1/1:8:291:0.2371
```

which have an allele frequency (sometimes far) below 0.25.

And while I know, that  "--call_snp_only" is declared as EXPERIMENTAL, I also would like to mention, that I get some seldom calls like these:

```
EFAU004_02496	296	.	GC	G	4.65	PASS	F	GT:GQ:DP:AF	0/1:4:255:0.1686
EFAU004_00620	132	.	A	AG	3.35	PASS	F	GT:GQ:DP:AF	1/1:3:246:0.1545
EFAU004_02332	95	.	GC	G	6.80	PASS	F	GT:GQ:DP:AF	0/1:6:287:0.1742
```

Do you have an idea, why these calls could slip by the used filters? Is there maybe a difference in the allele frequency used to filter out calls and the estimated allele frequency shown in the vcf file?

Thanks in advance

Sebastian

**Comment by zhengzhenxian** [comment]
Hi Sebastian,

Thanks for reporting. For the experimental `--call_snp_only` option,  the logic is that we only rely on `--snp_min_af` to select candidates for model prediction. The network might still possibly make Indel prediction or predict other alternative alleles below the specified `snp_min_af`. In the next release, we will use a different option name. For now, to get the best performance out of Clair3, we suggest using the default `snp_min_af` setting, and later remove variants with say `bcftools`.

**Comment by SebastianMeyer1989** [comment]
Thanks for your reply.
Aside from the "--call_snp_only" option I still do not understand, why I get so many calls below my chosen allele frequency threshold of 0.25.
But I will follow your suggestion and remove them with another tool after the calling.

**Comment by aquaskyline** [comment]
To further clarify, Clair3 first identifies variant candidates using some thresholds (AF, coverage, etc.). It then inputs these identified candidates into deep learning models to decide whether they are true variants as well as derive the characteristics of the true variants. `call_snp_only` and `snp_min_af` should be more appropriately renamed as `choose_only_snps_as_candidate` and `min_snp_af_for_candidate`, because they apply to identify variant candidates. The deep learning models have the ability to derive a different SNP allele or even an Indel from an SNP candidate, and that explains why you have seen indels or AF below the value you have set. The confusing option names were some developmental leftovers, we will change them in the next release.

**Comment by SebastianMeyer1989** [comment]
OK, now I understand.
Thank you very much for clarifying!
