### ISSUE TITLE
[ERROR] No full-alignment output for file

### ISSUE THREAD

**Issue by weishwu** [HKU-BAL/Clair3#181]
Hi,

I'm getting a lot of "[ERROR] No full-alignment output for file" error lines in the log. I got the "merge_output.vcf.gz" file which contains a lot of variants (5,774,275 PASS ones), but the "full_alignment.vcf.gz" file is empty except the header lines. There are "LowQual" variants as indicated in the FILTER column in "merge_output.vcf.gz". So what does the error mean and how should I fix it?
For the final variant calling results, should I use the "PASS" ones from "merge_output.vcf.gz", or the ones in "full_alignment.vcf.gz"?
I'm using version 1.0.0.
Thanks.

**Comment by zhengzhenxian** [comment]
Hi,

Could you send the logs `${OUPUT_DIR}/run_clair3.log` and `${OUPUT_DIR}/log` to my email [zxzheng@cs.hku.hk](mailto:zxzheng@cs.hku.hk) for us to pinpoint the full-alignment output issue? Thanks!

Zhenxian

**Comment by weishwu** [comment]
Hi Zhenxian,

I've sent you the email. Let me know if you need more data.

Thanks,

**Comment by zhengzhenxian** [comment]
Hi, Weisheng,

Thanks for sharing the logs! Upon review, we have determined that all full alignments failed due to gzip errors, which prevented any output from being generated.  The error messages present in your logs indicate this:
```
gzip: invalid magic
[E::faidx_adjust_position] The sequence "chr1:inf-0" was not found
[E::sam_itr_next] Null iterator
Total processed positions in chr1 (chunk 5/348) : 0
ESC[91m[ERROR] No full-alignment output for file chr1/xxx/full_alignment_output/full_alignment_chr1.4_348.vcfESC[0m
```

It seems that this issue is similar to a previous [issue](https://github.com/HKU-BAL/Clair3/issues/98). Are you using BioContainers for installation? We would suggest to use [docker image](https://github.com/HKU-BAL/Clair3#option-1--docker-pre-built-image) or [conda installation](https://github.com/HKU-BAL/Clair3#option-3--bioconda) instead.

**Comment by weishwu** [comment]
Hi Zhenxian,

Thanks for helping! It worked after I switched to hkubal/clair3:v0.1-r11.
