### ISSUE TITLE
FULL_ALN_FILE_*': No such file or directory

### ISSUE THREAD

**Issue by nhhaidee** [HKU-BAL/Clair3#198]
Hi @zhengzhenxian,

I have just used latest version (1.0.1) of Clair3, I got error in one of my sample. Please note that there is no error with v0.1-r10 which I have been using for a long time. Can you help take a look on this advice me if this is bug/error of new release

`
ls: cannot access 'ERR6359501.Segment_3_PA.CY146886.clair3/tmp/full_alignment_output/candidate_bed/FULL_ALN_FILE_*': No such file or directory
`

Please see below log for more details and let me know if need more information

Thanks,
Hai

  [INFO] 2/7 Select heterozygous SNP variants for Whatshap phasing and haplotagging
  [WARNING] Cannot find any 0/1 variant in pileup output using variant quality cut-off proportion: 0.19999999999999996, total heterozygous variants: 0
  [WARNING] Set low variant quality score cut-off to 0.0
  [INFO] Select heterozygous pileup variants exceeding phasing quality cutoff 0
  [INFO] Total heterozygous SNP positions selected: CY146886: 0
  
  real	0m0.317s
  user	0m0.238s
  sys	0m0.088s
  
  [INFO] 3/7 Phase VCF file using Whatshap
  This is WhatsHap 1.7 running under Python 3.9.0
  Working on 1 sample from 1 family
  
  # Resource usage
  Maximum memory usage: 0.038 GB
  Time spent reading BAM/CRAM:                    0.0 s
  Time spent parsing VCF:                         0.0 s
  Time spent selecting reads:                     0.0 s
  Time spent phasing:                             0.0 s
  Time spent writing VCF:                         0.0 s
  Time spent finding components:                  0.0 s
  Time spent on rest:                             0.0 s
  Total elapsed time:                             0.0 s
  
  real	0m0.491s
  user	0m0.385s
  sys	0m0.117s
  
  [INFO] 5/7 Select candidates for full-alignment calling
  [WARNING] Cannot find any low-quality 0/1 or 1/1 variant in pileup output using variant quality cut-off proportion: 0.7, total variants: 0
  [WARNING] Set low variant quality score cut-off to 0.0
  [INFO] Set variants quality cutoff 0.0
  [INFO] Set reference calls quality cutoff 6.0
  [WARNING] Cannot find any low-quality 0/0, 0/1 or 1/1 variant in pileup output in contig CY146886
  [INFO] Low quality reference calls to be processed in CY146886: 0
  [INFO] Low quality variants to be processed in CY146886: 0
  
  real	0m0.337s
  user	0m0.289s
  sys	0m0.052s
  
  [INFO] 6/7 Call low-quality variants using full-alignment model
  ls: cannot access 'ERR6359501.Segment_3_PA.CY146886.clair3/tmp/full_alignment_output/candidate_bed/FULL_ALN_FILE_*': No such file or directory
  [INFO] No Candidate found! Exit in selecting full-alignment candidates
  
  real	0m6.411s
  user	0m5.689s
  sys	0m0.743s
`

**Comment by zhengzhenxian** [comment]
Hi,

Seem no candidate was found in the pileup calling. We might need more details to pinpoint the missing variants. Could you send the logs `${OUPUT_DIR}/run_clair3.log` and `${OUPUT_DIR}/log` to my email zxzheng@cs.hku.hk? Thanks!

Zhenxian

**Comment by zhengzhenxian** [comment]
Hi, @nhhaidee,

Thank you for providing the logs. The warning message indicates that the full-alignment calling was skipped due to the detection of too few candidates. This issue is similar to a previously reported issue, which can be found at this link: https://github.com/HKU-BAL/Clair3/issues/108.

You might try to call a longer contig and let me know if the issue persists, thanks.

**Comment by mproberts99** [comment]
I've had the same issue recently. Makes sense that there are too few candidates. Perhaps it should still output variants found in pileup calling to the merge_output.vcf.gz? In my case, it was a small region from targeted sequencing and 2 non-reference variants were found (and 9 RefCall) during pileup, but this error caused it to skip full alignment calling and never produced a merged output vcf, therefore losing the two non-reference variants it did find

**Comment by nhhaidee** [comment]
I agree with @mproberts99 that it should still produce output `merge_output.vcf.gz`. It is particular important for automatic pipeline as our nf-flu pipeline, if one sample failed to produce output the the whole pipeline then stops immediately. Please note that for the same data, we have not had any problem with old version is v0.1-r10

**Comment by aquaskyline** [comment]
A fix scheduled in v1.0.2.

**Comment by nhhaidee** [comment]
Thanks @zhengzhenxian , we will update our automatic pipeline

**Comment by max-vdL** [comment]
Hi, I am using clair3 for a relatively small region and I frequently get no variants from the full_alignment step. This is expected and clair doesn't really crash (I still get the merge_output.vcf) but the gvcf doesn't get generated. This is not a big deal but means that I can't use the gvcf for downsteam processing as it's only present sometimes.

**Comment by max-vdL** [comment]
Certainly! I'm aligning to an ensembl cDNA reference, so my contig only has ~5k bases.

[INFO] CLAIR3 VERSION: v1.0.2
[INFO] BAM FILE PATH: /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1.sorted.bam
[INFO] REFERENCE FILE PATH: /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/Homo_sapiens.GRCh38.103_ABL1_ENST00000318560.6.fa
[INFO] MODEL PATH: /opt/models/r941_prom_sup_g5014
[INFO] OUTPUT FOLDER: /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1
[INFO] PLATFORM: ont
[INFO] THREADS: 12
[INFO] BED FILE PATH: /nanopanel2/roi.bed
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: 
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 500
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.8
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: True
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: True
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: True
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

+ /opt/bin/scripts/clair3_c_impl.sh --bam_fn /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1.sorted.bam --ref_fn /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/Homo_sapiens.GRCh38.103_ABL1_ENST00000318560.6.fa --threads 12 --model_path /opt/models/r941_prom_sup_g5014 --platform ont --output /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1 --bed_fn=/nanopanel2/roi.bed --vcf_fn=EMPTY --ctg_name=EMPTY --sample_name=SAMPLE --chunk_num=0 --chunk_size=500 --samtools=samtools --python=python3 --pypy=pypy3 --parallel=parallel --whatshap=whatshap --qual=2 --var_pct_full=0.7 --ref_pct_full=0.1 --var_pct_phasing=0.8 --snp_min_af=0.08 --indel_min_af=0.15 --min_mq=5 --min_coverage=2 --min_contig_size=0 --pileup_only=False --gvcf=True --fast_mode=False --call_snp_only=True --print_ref_calls=False --haploid_precise=False --haploid_sensitive=False --include_all_ctgs=False --no_phasing_for_fa=False --pileup_model_prefix=pileup --fa_model_prefix=full_alignment --remove_intermediate_dir=True --enable_phasing=False --enable_long_indel=False --keep_iupac_bases=False --use_gpu=False --longphase_for_phasing=False --longphase=EMPTY --use_whatshap_for_intermediate_phasing=True --use_longphase_for_intermediate_phasing=False --use_whatshap_for_final_output_phasing=False --use_longphase_for_final_output_phasing=False --use_whatshap_for_final_output_haplotagging=False

[INFO] Check environment variables
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/log
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/split_beds
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/merge_output
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/phase_output
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/gvcf_tmp_output
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/full_alignment_output
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/phase_output/phase_vcf
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/phase_output/phase_bam
[INFO] Create folder /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/full_alignment_output/candidate_bed
[INFO] --include_all_ctgs not enabled, use chr{1..22,X,Y} and {1..22,X,Y} by default
[INFO] Call variant in contigs: ENST00000318560.6
[INFO] Chunk number for each contig: 12
[INFO] 1/7 Call variants using pileup model
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 1/12) : 0
Total time elapsed: 1.41 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_1.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 5/12) : 0
Total time elapsed: 1.78 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_5.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 2/12) : 0
Total time elapsed: 1.90 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_2.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 7/12) : 0
Total time elapsed: 2.33 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_7.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 6/12) : 0
Total time elapsed: 2.41 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_6.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 4/12) : 0
Total time elapsed: 2.40 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_4.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 3/12) : 0
Total time elapsed: 2.48 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_3.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 9/12) : 0
Total time elapsed: 2.54 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_9.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 8/12) : 1
Total time elapsed: 6.33 s
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 10/12) : 0
Total time elapsed: 1.92 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_10.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 11/12) : 0
Total time elapsed: 2.12 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_11.vcf, remove empty file
Calling variants ...
Total processed positions in ENST00000318560.6 (chunk 12/12) : 0
Total time elapsed: 2.10 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/pileup_output/pileup_ENST00000318560.6_12.vcf, remove empty file

real	0m16.738s
user	0m52.124s
sys	0m9.869s

[INFO] 2/7 Select heterozygous SNP variants for Whatshap phasing and haplotagging
[93m[WARNING] Cannot find any 0/1 variant in pileup output using variant quality cut-off proportion: 0.19999999999999996, total heterozygous variants: 0[0m
[93m[WARNING] Set low variant quality score cut-off to 0.0[0m
[INFO] Select heterozygous pileup variants exceeding phasing quality cutoff 0
[INFO] Total heterozygous SNP positions selected: ENST00000318560.6: 1

real	0m0.481s
user	0m0.301s
sys	0m0.086s

[INFO] 3/7 Phase VCF file using Whatshap
This is WhatsHap 1.7 running under Python 3.9.0
Working on 1 sample from 1 family

# Working on contig ENST00000318560.6 in individual SAMPLE
Found 1 usable heterozygous variants (0 skipped due to missing genotypes)
Found 26375 reads covering 1 variants
Kept 0 reads that cover at least two variants each
Selected 0 most phase-informative reads covering 0 variants
Phasing 1 sample by solving the MEC problem ...
No. of phased blocks: 0

# Resource usage
Maximum memory usage: 0.064 GB
Time spent reading BAM/CRAM:                    1.3 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent phasing:                             0.0 s
Time spent writing VCF:                         0.0 s
Time spent finding components:                  0.0 s
Time spent on rest:                             1.1 s
Total elapsed time:                             2.4 s

real	0m3.038s
user	0m1.754s
sys	0m0.207s

[INFO] 5/7 Select candidates for full-alignment calling
[93m[WARNING] Cannot find any low-quality 0/1 or 1/1 variant in pileup output using variant quality cut-off proportion: 0.7, total variants: 1[0m
[93m[WARNING] Set low variant quality score cut-off to 0.0[0m
[93m[WARNING] Cannot find any low-quality 0/0 reference calls in pileup output using reference quality cut-off proportion: 0.1, total reference calls: 0[0m
[93m[WARNING] Set low reference quality score cut-off to 0.0[0m
[INFO] Set variants quality cutoff 0.0
[INFO] Set reference calls quality cutoff 0.0
[93m[WARNING] Cannot find any low-quality 0/0, 0/1 or 1/1 variant in pileup output in contig ENST00000318560.6[0m
[93m[WARNING] Copying pileup.vcf.gz to /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/merge_output.vcf.gz[0m
[INFO] Low quality reference calls to be processed in ENST00000318560.6: 0
[INFO] Low quality variants to be processed in ENST00000318560.6: 0

real	0m0.561s
user	0m0.394s
sys	0m0.084s

[INFO] 6/7 Call low-quality variants using full-alignment model
Calling variants ...
Total processed positions in  : 0
[91m[ERROR] No full-alignment output for file //nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/full_alignment_output/full_alignment_.vcf[0m
Total time elapsed: 0.01 s
[INFO] No vcf output for file /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/full_alignment_output/full_alignment_.vcf, remove empty file

real	0m3.442s
user	0m3.006s
sys	0m0.294s
[93m[WARNING] No vcf file found with prefix:/nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/tmp/full_alignment_output/full_alignment, output empty vcf file[0m
[93m[WARNING] Copying pileup.vcf.gz to /nanopanel2/flongle_33/nanoseq/work/ee/c251aa1692053983ef563124e69805/S01_R1/merge_output.vcf.gz[0m
[INFO] Exit in full-alignment variant calling

real	0m30.336s
user	0m59.029s
sys	0m11.925s

**Comment by max-vdL** [comment]
In case anyone else has the same problem: I worked around it by lowering the --snp_min_af to 0.01 and specifying --print_ref_calls. That way both the pileup and the full_alignment approach always have something to report and nothing breaks. This leads to a much larger output of course, so it should only be used for small regions.
