### ISSUE TITLE
Missing variants in one contig

### ISSUE THREAD

**Issue by mproberts99** [HKU-BAL/Clair3#216]
Hi,
I am using Clair3 for variant calling on targeted amplicon sequencing data. Since we are using the R10 flowcell and the model provided by ONT was trained at 60x depth, we subsample the bam to 60x prior to variant calling. When the caller goes through pileup calling, it does not identify any variant candidates in one of the contigs (chr6), despite there being obvious variants in the bam file when viewing in IGV. This has happened to at least two samples. I have attached the log and can send the VCF/bam files as needed for troubleshooting.
[run_clair3.log](https://github.com/HKU-BAL/Clair3/files/12346309/run_clair3.log)

**Comment by aquaskyline** [comment]
It looked like no candidate was found in chr6. If you want us to take a deeper look, please send us a mini bam with reads in chr6 only.

**Comment by oneillkza** [comment]
We've also noticed that Clair3 tends to just skip contigs if it encounters any errors with them. e.g. we had a couple of samples in a large run where there was network instability while they were running, which caused about half of the contigs to fail because the subprocesses working on them couldn't read them.

**Comment by zhengzhenxian** [comment]
@mproberts99,

Thank you for providing the log and data. We noticed that all the reads in your chr6 BAM file have a mapping quality of 1. Those low-MQ reads(MQ < 5) were filtered by Clair3 and no candidate was outputted. The variants present in the low-MQ reads are likely to be false variants caused by alignment artifacts.
