### ISSUE TITLE
Clair3 silently ignores read errors

### ISSUE THREAD

**Issue by oneillkza** [HKU-BAL/Clair3#219]
We had a situation recently where a couple of samples in a large run happened to run at a time when there was network instability on our cluster. This caused about half of the chunks to fail because the subprocesses working on them couldn't read them. But it seems clair3's behaviour when chunks fail is to just ignore them. (Presumably this is due to repetitive regions, chrY, etc where failure is expected to be a frequent occurrence.) So what happened was that Clair3 just ran to completion with a perfunctory note in the logs, compiling the remaining chunks into a very incomplete vcf file. So the surrounding NextFlow workflow had no way of knowing that an error had occurred, and we didn't even pick this up until some time later when doing downstream analyses.

It would be helpful if clair3 could detect errors due to things like file I/O failing, and fail the run in those cases.

**Comment by aquaskyline** [comment]
Clair3 stops at I/O errors. Network-mounted drives are trickier because it depends on your mounting parameters. Some parameters allow data to be (discarded on errors)[https://unix.stackexchange.com/questions/267138/preventing-broken-nfs-connection-from-freezing-the-client-system]. Clair3 can't handle that because the OS is telling Clair3 the data is fine.
