### ISSUE TITLE
Does Clair3 take into account indels proximity when calling SNPs?

### ISSUE THREAD

**Issue by Axze-rgb** [HKU-BAL/Clair3#268]
Hello, this used to be an issue that, when calling SNPs, indels were responsible for false positives. Bcftools even implemented a filter called SnpGap: Filter SNPs within <int> base pairs of an indel (the default) or any combination of indel,mnp,bnd,other,overlap

So far I haven't encountered SNPs which were "obviously" false due to an indel, but I was wondering if it's something you had investigated: does Clair3 reject SNPs very close to indels? I am aware that it's probably a double edge swords to implement a filter such as "all SNP in + or - 3 bases of the indels become TN (true negative)". 

Thanks a lot

**Comment by aquaskyline** [comment]
It's a common and bit ancient hard filter that back in the days, it generally did more good than harm. As you mentioned, it's a double edge sword, and since we are now at the stage of competing for small decimal changes above 99.7% for SNP calling, the hard filter can hardly strike a balance if not doing more harm (i.e. leading to more FN and the FPs removed). The hard filter is easy to use and are already there in a few VCF processing tools, so one can try them.
