### ISSUE TITLE
Using HERRO corrected reads in Clair3

### ISSUE THREAD

**Issue by KANGYUlab** [HKU-BAL/Clair3#329]
Hi developers,

Thanks for the great tool!

Does Clair3 work with herro-corrected ONT reads? If so, what model should be used?

Thanks.

**Comment by aquaskyline** [comment]
Yes, theoretically, Clair3 works with HERRO-corrected reads. The model same as the one to be used for uncorrected reads should be chosen. As HERRO is still undergoing rapid improvements, we have not yet systematically benchmarked what HERRO-corrected reads would bring to the variants called by Clair3. Some ad hoc benchmarks so far suggested that the calling performance is not much different between using uncorrected and HERRO-corrected reads. It makes sense because no matter it is "uncorrected->HERRO->Clair3" or "uncorrected->Clair3", the very first input remained the same, thus to Clair3, no additional raw information was provided. Nevertheless, how to make the best when using HERRO and Clair3 together remains to be systematically studied.

**Comment by KANGYUlab** [comment]
Thank you so much. I have tried; it works well with herro corrected reads.
