### ISSUE TITLE
Bioconda install issue - Illumina only

### ISSUE THREAD

**Issue by holtjma** [HKU-BAL/Clair3#42]
Hi, 

I semi-recently discussed an issue with installing via Conda locally (#29), and I think that issue is persisting in the bioconda builds.

When I run with the PacBio models, I don't get any issues.  However, when I run with the Illumina models, I get the following error:
```
OSError: Cannot load library <PATH>/conda/46cb01a3/bin/preprocess/realign/realigner: <PATH>/conda/46cb01a3/bin/preprocess/realign/realigner: cannot open shared object file: No such file or directory
```

I think this can be resolved by adding the compile instructions in #29 to the [build file](https://github.com/bioconda/bioconda-recipes/blob/07055a9cb7daa2a487e25e856c7e649795c1653e/recipes/clair3/build.sh#L6) so that the binary objects are automatically created during the conda install.

**Comment by aquaskyline** [comment]
Thank you @holtjma for the suggestion. There are additional [installation steps](https://github.com/HKU-BAL/Clair3/blob/main/docs/quick_demo/illumina_quick_demo.md#step-2-install-boost-graph-library-for-illumina-realignment-process) for using Clair3 with Illumina. The additional steps are currently standalone because the C++ boost library installation is taking around 15 minutes and 500MB of disk space more. This makes the price of deploying Clair3 much higher while the Clair3 modules for Illumina calling are not always needed. In fact, only the boost graph library was used in Clair3, but so far, we can't find a standalone boost graph library from anaconda, thus we are installing the whole library instead. Compiling the boost graph library from source code is also not an option because of the overhead of preparing a build environment.

But anyway, to address your demand, we are creating a new bioconda package named `clair3-illumina` that is separated from `clair3`. The code of the two packages is the same, except that `clair3-illumina` will install the modules for Illumina input by default. The `clair3-illumina` package will for sure take longer and much disk space to install.

We will post here when `clair3-illumina` is available.

**Comment by holtjma** [comment]
Ah, I see.  I wasn't aware of the additional problems around the install.  However, that seems completely reasonable to me, especially since these environments are usually only built once.

**Comment by zhengzhenxian** [comment]
Hi,

We have added the `clair3-illumina`([link](https://anaconda.org/bioconda/clair3-illumina)) package in bioconda to call Illumina data. The version is in sync with Clair3 latest version. Please feel free to have a try.

Thanks!

**Comment by holtjma** [comment]
Awesome, I think a lot of people will appreciate this (clair3 is quite awesome IMO)!  Thanks for putting it together so quickly!
