### ISSUE TITLE
Should supplementary alignment be considered in variant calling of bacterial genome?

### ISSUE THREAD

**Issue by llk578496** [HKU-BAL/Clair3#67]
Hi,

I am having a set of ONT data for bacteria WGS, I used minimap2 with default params for mapping, and I see both at the start and end of the reference genome are having many supplementary alignments (may be due to the circular genome of bacteria?). 
In Clair3, seems like the supplementary alignments will be discarded (as mentioned in #54). 
May I know it is good to include the supplementary alignment to be considered in variant calling?

**Comment by zhengzhenxian** [comment]
Our early observation is that supplementary alignments lower the short variant calling performance a bit in the human genome. We are not sure about bacteria data. To test out, one can switch `SAMTOOLS_VIEW_FILTER_FLAG = 2316` to `SAMTOOLS_VIEW_FILTER_FLAG = 268` in `shared/param_p.py` and `shared/param_f.py`. Please let us know if using supplementary alignment turns out to give better performance.

**Comment by llk578496** [comment]
Thank you @zhengzhenxian !
Sure I will try that out!
Also I would like to know what if I only call SNP? Will the supplementary alignments lower the performance?

**Comment by zhengzhenxian** [comment]
In the human genome, yes.
